# Generated by Django 4.2.2 on 2023-08-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LRS_App', '0002_uploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='upload_datetime',
            new_name='upload_date',
        ),
    ]
