# Generated by Django 4.2.2 on 2023-08-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LRS_App', '0003_rename_upload_datetime_uploadedfile_upload_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='upload_date',
            new_name='upload_datetime',
        ),
    ]
