# Generated by Django 4.2.2 on 2023-08-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LRS_App', '0004_rename_upload_date_uploadedfile_upload_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='upload_datetime',
        ),
    ]
