# Generated by Django 4.2.2 on 2023-08-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LRS_App', '0005_remove_uploadedfile_upload_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
