# Generated by Django 4.2.2 on 2023-08-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LRS_App', '0006_uploadedfile_uploaded_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_datetime',
            field=models.DateTimeField(),
        ),
    ]
