# Generated by Django 4.2.2 on 2023-08-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LRS_App', '0008_alter_uploadedfile_uploaded_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='filetype',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
