# Generated by Django 4.2.2 on 2023-08-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LRS_App', '0009_uploadedfile_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='top_resource',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
