# Generated by Django 4.2.2 on 2023-08-18 12:41

import builtins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LRS_App', '0010_uploadedfile_top_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('plan', models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Pusiness', 'Business'), ('Premium', 'Premium'), ('VIP', 'VIP')], max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=builtins.callable, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
