# Generated by Django 4.2.2 on 2023-08-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LRS_App', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
