# Generated by Django 4.2.2 on 2023-08-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LRS_App', '0012_remove_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Business', 'Business'), ('Premium', 'Premium'), ('VIP', 'VIP')], max_length=10, null=True),
        ),
    ]
