# Generated by Django 4.2.2 on 2023-08-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LRS_App', '0013_alter_userprofile_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('business', 'Business'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=10, null=True),
        ),
    ]
