# Generated by Django 4.2.2 on 2023-08-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LRS_App', '0015_downloadtracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadTracking',
        ),
    ]
